import Head from 'next/head'
import ContactBar from '../components/contact-bar'
import Main from '../components/main'
import styles from '../styles/home.module.scss'
import { getSortedPostsData } from '../lib/posts'
import PostList from '../components/post-list'

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData,
    },
  }
}

export default function Home({ allPostsData }) {
  return (
    <>
      <Head>
        <title>Dirty Carrots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/carrot-ico.svg" />
      </Head>

      <div className={styles.wrapper}>
        <Main />
        <PostList posts={allPostsData} />
        <ContactBar />
      </div>
    </>
  )
}
