import Head from 'next/head'
import Footer from '../components/footer'
import Main from '../components/main'
import styles from '../styles/home.module.scss'
import { getSortedPostsData } from '../lib/posts'
import PostList from '../components/post-list'
import WorkInProgress from '../components/work-in-progress'

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()

  return {
    props: {
      allPostsData,
    },
  }
}

export default function Home({ allPostsData }) {
  return (
    <>
      <Head>
        <title>Dirty Carrots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/carrot-ico.svg" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@600;800&family=Roboto+Condensed:wght@400;700&display=swap');
        </style>
      </Head>

      <div className={styles.wrapper}>
        <WorkInProgress />
        <Main />
        <PostList posts={allPostsData} />
        <Footer />
      </div>
    </>
  )
}
