import Head from 'next/head'
import Layout from '../components/layout'

export default function KitchenSink() {
  return (
    <Layout>
      <Head>
        <title>Kitchen Sink | Dirty Carrots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/carrot-ico.svg" />
      </Head>

      <header role="banner">
        <h1>HTML5 Kitchen Sink</h1>
        <small>
          <a href="#headings">Headings</a> |{' '}
          <a href="#paragraphs">Paragraphs</a> |{' '}
          <a href="#phrasing">Phrasing</a> |{' '}
          <a href="#palpable">Palpable Content</a> |{' '}
          <a href="#embeds">Embeds</a> | <a href="#forms">Forms</a> |{' '}
          <a href="#tables">Tables</a>{' '}
        </small>{' '}
        <br />
        <br />
      </header>
      <hr />
      <main>
        <section id="headings">
          <h3>Headings</h3>
          <hgroup>
            <h1>I am an h1.</h1>
            <h2>I am an h2.</h2>
            <h3>I am an h3.</h3>
            <h4>I am an h4</h4>
            <h5>I am an h5.</h5>
            <h6>I am an h6.</h6>
          </hgroup>
        </section>
        <hr />
        <section id="paragraphs">
          <h3>Paragraph Blocks</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a
            ipsum elit. In quis volutpat dui, in consequat tellus. Praesent
            molestie vehicula neque, dignissim gravida erat porta ornare. Etiam
            facilisis odio vulputate dui pharetra, nec faucibus erat finibus.
            Duis eget nibh nec lacus ultrices vestibulum sit amet sit amet
            dolor. Pellentesque lacinia dolor ut dui lacinia maximus. Donec id
            eleifend purus. Maecenas dictum nisi et tincidunt ornare. Fusce
            volutpat pretium est.
          </p>
          <p>
            Ut vel pulvinar augue. Vestibulum gravida vitae ligula ut luctus.
            Nulla dui purus, accumsan sollicitudin tellus in, pretium eleifend
            elit. Pellentesque varius enim in sem fringilla, a tincidunt orci
            laoreet. Donec in faucibus purus, nec cursus augue. Proin magna
            lectus, efficitur ut lobortis at, iaculis sed ligula. Sed pulvinar
            vulputate turpis, sed viverra magna vestibulum eleifend. Phasellus
            ac sodales diam. Nam a commodo magna. Fusce condimentum risus
            tellus. Nullam luctus quam neque, sit amet eleifend lectus fermentum
            non.
          </p>
          <uL>
            <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
            <li>Donec ac enim vel sapien blandit semper sed ut lorem.</li>
            <li>
              Integer tempus libero ut est commodo, vitae tincidunt augue
              eleifend.
            </li>
            <li>Fusce non mi in ex rutrum sagittis.</li>
            <li>
              Maecenas ut mauris pharetra, ultrices arcu ac, volutpat sem.
            </li>
          </uL>
          <p>
            Aliquam sit amet enim at massa accumsan convallis eget ut augue.
            Aliquam euismod massa ut felis rutrum interdum. Duis egestas nisi et
            pretium lacinia. Nunc id massa ut elit pretium posuere ac imperdiet
            metus. Quisque id justo blandit, mattis tortor feugiat, posuere
            quam. Duis eget mi non diam semper mollis. Curabitur in placerat
            dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus.
            Etiam in orci est.
          </p>
        </section>
        <hr />
        <section id="phrasing">
          <h3>blockquote</h3>

          <blockquote>
            Healthy soil is critical to successful agriculture and is vital to
            produce the food and fiber we use every day. When soil issues arise,
            from soil organism habitat degradation to erosion to nutrient
            depletion, they can have long-term and costly impacts to soil health
            and production goals.
            <footer>
              Steve Jobs,{' '}
              <cite>Apple Worldwide Developers&apos; Conference, 1997</cite>
            </footer>
          </blockquote>
          <p>
            <code>details</code> and <code>summary</code>:
          </p>
          <details>
            <summary>
              Copying... <progress max="375505392" value="97543282"></progress>{' '}
              25%
            </summary>
            <dl>
              <dt>Transfer rate:</dt>
              <dd>452KB/s</dd>
              <dt>Duration:</dt>
              <dd>01:16:27</dd>
              <dt>Color profile:</dt>
              <dd>SD (6-1-6)</dd>
              <dt>Dimensions:</dt>
              <dd>320×240</dd>
            </dl>
          </details>
          <p>
            <code>dl</code>:
          </p>
          <dl>
            <dt>Definition List Title</dt>
            <dd>Definition list division.</dd>
            <dt>Kitchen Sink</dt>
            <dd>
              Used in expressions to describe work in which all conceivable (and
              some inconceivable) sources have been mined. In this case, a bunch
              of markup.
            </dd>
            <dt>aside</dt>
            <dd>Defines content aside from the page content</dd>
            <dt>blockquote</dt>
            <dd>Defines a section that is quoted from another source</dd>
          </dl>
          <p>
            <code>figure</code>:
          </p>
          <figure>
            <img src="https://www.fillmurray.com/402/295" />
            <figcaption>
              Figure 1: A picture of Bill Murray from{' '}
              <a href="https://www.fillmurray.com/">fillmurray.com</a>
            </figcaption>
          </figure>
          <br />
          <br />
          <h4 id="forms">
            <a href="#forms">#</a> Forms
          </h4>
          <hr />
          <form>
            <p>
              <label htmlFor="example-input-email">Email address</label>
              <input type="email" id="example-input-email" />
            </p>
            <p>
              <label htmlFor="example-input-number">Number</label>
              <input type="number" id="example-input-number" />
            </p>
            <p>
              <label htmlFor="example-input-password">Password</label>
              <input type="password" id="example-input-password" />
            </p>
            <p>
              <label htmlFor="example-input-search">Search</label>
              <input type="search" id="example-input-search" />
            </p>
            <p>
              <label htmlFor="example-input-tel">Telephone number</label>
              <input type="tel" id="example-input-tel" />
            </p>
            <p>
              <label htmlFor="example-input-text">Text</label>
              <input type="text" id="example-input-text" />
            </p>
            <p>
              <label htmlFor="example-input-readonly">Read-only</label>
              <input type="text" readOnly value="Can't touch this!" />
            </p>
            <p>
              <label htmlFor="example-input-disabled">Disabled</label>
              <input type="text" disabled value="Not available" />
            </p>
            <p>
              <label htmlFor="example-input-url">URL</label>
              <input type="url" id="example-input-url" />
            </p>
            <p>
              <label htmlFor="example-input-color">Color</label>
              <input type="color" id="example-input-color" />
            </p>
            <p>
              <label htmlFor="example-input-date">Date</label>
              <input type="date" id="example-input-date" />
            </p>
            <p>
              <label htmlFor="example-input-date-time">Date / Time</label>
              <input type="dateTime" id="example-input-date-time" />
            </p>
            <p>
              <label htmlFor="example-input-date-time-local">
                Date / Time local
              </label>
              <input type="dateTime-local" id="example-input-date-time-local" />
            </p>
            <p>
              <label htmlFor="example-input-month">Month</label>
              <input type="month" id="example-input-month" />
            </p>
            <p>
              <label htmlFor="example-input-week">Week</label>
              <input type="week" id="example-input-week" />
            </p>
            <p>
              <label htmlFor="example-input-time">Time</label>
              <input type="time" id="example-input-time" />
            </p>
            <p>
              <label htmlFor="example-input-file">File input</label>
              <input type="file" id="example-input-file" />
            </p>
            <p>
              <label htmlFor="example-input-range">Range input</label>
              <input
                type="range"
                id="example-input-range"
                min="1"
                max="4"
                value="3"
              />
            </p>
            <p>
              <label htmlFor="example-select1">Select</label>
              <select id="example-select1">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </p>
            <p>
              <label htmlFor="example-select1a">Select with size</label>
              <select id="example-select1a" size="2">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </p>
            <p>
              <label htmlFor="example-select2">Multiple select</label>
              <select multiple id="example-select2">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </p>
            <p>
              <label htmlFor="example-optgroup">
                Select with optgroup: Favorite Car
              </label>
              <select id="example-optgroup">
                <optgroup label="Swedish Cars">
                  <option>Volvo</option>
                  <option>Saab</option>
                </optgroup>
                <optgroup label="German Cars">
                  <option>Mercedes</option>
                  <option>Audi</option>
                </optgroup>
              </select>
            </p>
            <p>
              <label htmlFor="example-optgroup2">
                Select with optgroup and size:Favorite Dish
              </label>
              <select id="example-optgroup2" size="2">
                <optgroup label="Vegetarian">
                  <option>Green Salad</option>
                  <option>French Fries</option>
                </optgroup>
                <optgroup label="Carnivorous">
                  <option>Big Mac</option>
                  <option>Roast Beef</option>
                </optgroup>
              </select>
            </p>
            <p>
              <label htmlFor="example-optgroup3">
                Multiple select with optgroup: Public transport
              </label>
              <select id="example-optgroup3" multiple>
                <optgroup label="Ground">
                  <option>Train</option>
                  <option>Bus</option>
                </optgroup>
                <optgroup label="Water">
                  <option>Ship</option>
                  <option>Submarine</option>
                </optgroup>
                <optgroup label="Air">
                  <option>Plane</option>
                  <option>Balloon</option>
                </optgroup>
              </select>
            </p>
            <p>
              <label htmlFor="example-textarea">Textarea</label>
              <textarea id="example-textarea" rows="3"></textarea>
            </p>
            <fieldset>
              <legend>I am legend</legend>
              <div>
                <input
                  type="radio"
                  name="option-radio"
                  id="option-radio1"
                  value="option1"
                  checked
                />
                <label htmlFor="option-radio1">
                  Option one is this and that&mdash;be sure to include why
                  it&apos;s great
                </label>
              </div>
              <div>
                <input
                  type="radio"
                  name="option-radio"
                  id="option-radio2"
                  value="option2"
                />
                <label>
                  Option two can be something else and selecting it will
                  deselect option one
                </label>
              </div>
              <div>
                <input
                  type="radio"
                  name="option-radio"
                  id="option-radio3"
                  value="option3"
                  disabled
                />
                <label>Option three is disabled</label>
              </div>
            </fieldset>
            <fieldset>
              <legend>I am also legend</legend>
              <input type="checkbox" id="checkbox1" />
              <label htmlFor="checkbox1">Check me out</label>
              <input type="checkbox" id="checkbox2" />
              <label htmlFor="checkbox2">and/or check me out</label>
            </fieldset>
            <p>
              <button type="button" name="button">
                Button
              </button>
              <input type="button" name="input" value="Input Button" />
              <input type="submit" name="submit" value="Input Submit" />
              <button type="submit" name="submit2">
                Submit
              </button>
              <input type="reset" name="reset" value="Input Reset" />
              <button type="reset" name="reset2">
                Reset
              </button>
              <button disabled>Cancel</button>
            </p>
          </form>
          <p>
            <code>ul</code> and <code>ol</code>:
          </p>
          <ul>
            <li>
              Unordered List item one
              <ul>
                <li>
                  Nested list item
                  <ul>
                    <li>Level 3, item one</li>
                    <li>Level 3, item two</li>
                    <li>Level 3, item three</li>
                    <li>Level 3, item four</li>
                  </ul>
                </li>
                <li>List item two</li>
                <li>List item three</li>
                <li>List item four</li>
              </ul>
            </li>
            <li>List item two</li>
            <li>List item three</li>
            <li>List item four</li>
          </ul>
          <ol>
            <li>
              List item one
              <ol>
                <li>
                  List item one
                  <ol>
                    <li>List item one</li>
                    <li>List item two</li>
                    <li>List item three</li>
                    <li>List item four</li>
                  </ol>
                </li>
                <li>List item two</li>
                <li>List item three</li>
                <li>List item four</li>
              </ol>
            </li>
            <li>List item two</li>
            <li>List item three</li>
            <li>List item four</li>
          </ol>
          <p>
            <code>output</code>:
          </p>
          {/* <form onsubmit="return false" oninput="o.value= a.valueAsNumber + b.valueAsNumber">
        <input name=a type=number step=any> +
        <input name=b type=number step=any> =
        <output name=o for="a b"></output>
      </form> */}
          <p>
            <code>pre</code>:
          </p>
          {/* <pre>
            display: block; padding: 7px; background-color: #F5F5F5; border: 1px
            solid #E1E1E8; border-radius: 3px; white-space: pre-wrap;
            word-break: break-all; font-family: Menlo, Monaco; line-height:
            160%;
          </pre> */}
          {/* <pre>
            <samp>
              You are in an open field west of a big white house with a boarded
              front door. There is a small mailbox here.
            </samp>{' '}
            <kbd>open mailbox</kbd>
            <samp>Opening the mailbox reveals: A leaflet.</samp>
          </pre> */}
          <br />
          <br />
          <h4 id="tables">
            <a href="#tables">#</a> Tables
          </h4>
          <hr />
          <table>
            <caption>Tables can have captions now.</caption>
            <tbody>
              <tr>
                <th>Person</th>
                <th>Number</th>
                <th>Third Column</th>
              </tr>
              <tr>
                <td>Someone Lastname</td>
                <td>900</td>
                <td>Nullam quis risus eget urna mollis ornare vel eu leo.</td>
              </tr>
              <tr>
                <td>
                  <a href="#">Person Name</a>
                </td>
                <td>1200</td>
                <td>
                  Vestibulum id ligula porta felis euismod semper. Donec
                  ullamcorper nulla non metus auctor fringilla.
                </td>
              </tr>
              <tr>
                <td>Another Person</td>
                <td>1500</td>
                <td>
                  Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor
                  auctor. Nullam id dolor id nibh ultricies vehicula ut id elit.
                </td>
              </tr>
              <tr>
                <td>Last One</td>
                <td>2800</td>
                <td>
                  Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
                  Cras mattis consectetur purus sit amet fermentum.
                </td>
              </tr>
            </tbody>
          </table>
          <p id="table-summary">
            In the following table, characteristics are given in the second
            column, with the negative side in the left column and the positive
            side in the right column.
          </p>
          <table aria-describedby="table-summary">
            <caption>Characteristics with positive and negative sides</caption>
            <thead>
              <tr>
                <th id="n">Negative</th>
                <th>Characteristic</th>
                <th id="p">Positive</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td headers="n r1">Sad</td>
                <th id="r1">Mood</th>
                <td headers="p r1">Happy</td>
              </tr>
              <tr>
                <td headers="n r2">Failing</td>
                <th id="r2">Grade</th>
                <td headers="p r2">Passing</td>
              </tr>
            </tbody>
          </table>
          <table>
            <caption>
              Complex table with a <code>thead</code>, multiple{' '}
              <code>tbody</code> elements, and a <code>tfoot</code>.
            </caption>
            <thead>
              <tr>
                <th></th>
                <th>2008</th>
                <th>2007</th>
                <th>2006</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>Net sales</th>
                <td>$32,479</td>
                <td>$24,006</td>
                <td>$19,315</td>
              </tr>
              <tr>
                <th>Cost of sales</th>
                <td>21,334</td>
                <td>15,852</td>
                <td>13,717</td>
              </tr>
            </tbody>
            <tbody>
              <tr>
                <th>Gross margin</th>
                <td>$11,145</td>
                <td>$8,154</td>
                <td>$5,598</td>
              </tr>
            </tbody>
            <tfoot>
              <tr>
                <th>Gross margin percentage</th>
                <td>34.3%</td>
                <td>34.0%</td>
                <td>29.0%</td>
              </tr>
            </tfoot>
          </table>
          <footer>
            <p>
              See the{' '}
              <a
                target="_blank"
                rel="noreferrer"
                href="https://www.w3.org/TR/html5/dom.html#palpable-content"
              >
                Palpable Content spec.
              </a>
            </p>
          </footer>
        </section>
        <hr />
        <section id="embeds">
          <header>
            <h3>
              <a href="#embeds">#</a> Embeds
            </h3>
            <p>
              Elements <code>audio</code>, <code>canvas</code>,{' '}
              <code>embed</code>,<code>iframe</code>, <code>img</code>,{' '}
              <code>math</code>, <code>object</code>,<code>picture</code>,{' '}
              <code>svg</code>, <code>video</code> make up the{' '}
              <em>embedded content</em> category.
            </p>
          </header>
          <p>
            <code>audio</code>:{' '}
            <audio
              controls
              src="https://upload.wikimedia.org/wikipedia/commons/c/c7/What_hath_God_wrought.ogg"
            ></audio>{' '}
            By Cqdx [
            <a href="https://creativecommons.org/licenses/by-sa/3.0">
              CC BY-SA 3.0{' '}
            </a>
            ],{' '}
            <a href="https://commons.wikimedia.org/wiki/File:What_hath_God_wrought.ogg">
              from Wikimedia Commons
            </a>
            .
          </p>
          <p>
            <code>iframe</code>:{' '}
            <iframe
              sandbox
              srcDoc="<h1>Sample Document</h1><p>This
is a sample content.</p>"
            ></iframe>
          </p>
          <p>
            <code>img</code>:{' '}
            <img src="https://www.fillmurray.com/150/150" alt="Bill Murray" />
          </p>
          <p>
            <code>math</code>:
          </p>
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <mtable>
              <mtr>
                <mtd>
                  <mtext>Quadratic Equation</mtext>
                </mtd>
                <mtd>
                  <mrow>
                    <mi>x</mi>
                    <mo>=</mo>
                    <mfrac>
                      <mrow>
                        <mo>-</mo>
                        <mi>b</mi>
                        <mo>&#x00B1;</mo>
                        <msqrt>
                          <mrow>
                            <msubsup>
                              <mi>b</mi>
                              <mrow></mrow>
                              <mn>2</mn>
                            </msubsup>
                            <mo>-</mo>
                            <mn>4</mn>
                            <mi>a</mi>
                            <mi>c</mi>
                          </mrow>
                        </msqrt>
                      </mrow>
                      <mrow>
                        <mn>2</mn>
                        <mi>a</mi>
                      </mrow>
                    </mfrac>
                  </mrow>
                </mtd>
              </mtr>
            </mtable>
          </math>
          <p>
            <code>picture</code>:
            <picture>
              <source
                srcSet="https://www.fillmurray.com/240/300 2x,
https://www.fillmurray.com/120/150 1x"
              />
              <img src="https://www.fillmurray.com/120/150" alt="Bill Murray" />
            </picture>
          </p>
          <p>
            <code>svg</code>:{' '}
            <svg
              role="presentation"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M19.199 24C19.199 13.467
10.533 4.8 0 4.8V0c13.165 0 24 10.835 24 24h-4.801zM3.291
17.415c1.814 0 3.293 1.479 3.293 3.295 0 1.813-1.485 3.29-3.301
3.29C1.47 24 0 22.526 0 20.71s1.475-3.294 3.291-3.295zM15.909
24h-4.665c0-6.169-5.075-11.245-11.244-11.245V8.09c8.727 0 15.909
7.184 15.909 15.91z"
              />
            </svg>
          </p>
          <p>
            <code>video</code>:{' '}
            <video
              controls
              src="https://upload.wikimedia.org/wikipedia/commons/b/b8/Dwarf_hamsters_running_on_disc_2.ogv"
            ></video>
          </p>
          <footer>
            <p>
              See the{' '}
              <a
                target="_blank"
                rel="noreferrer"
                href="https://www.w3.org/TR/html5/dom.html#embedded-content"
              >
                Embedded Content spec.
              </a>
            </p>
          </footer>
        </section>
        <hr />
      </main>
    </Layout>
  )
}
